In [ ]:
import pandas as pd

Question 1: What's the version of Pandas that you installed?

Answer: 1.5.3

In [ ]:
pd.__version__

'1.5.3'

In [ ]:
data = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv")

Question 2: How many columns are in the dataset?

Answer:10

In [ ]:
num_columns = data.shape[1]
num_columns

10

Question 3: Which columns in the dataset have missing values?
Answer: total_bedrooms    (207 missing values)

In [ ]:
data.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [ ]:
missing_values = data.isnull().sum()

In [ ]:
columns_with_missing_values = missing_values[missing_values > 0]
columns_with_missing_values

total_bedrooms    207
dtype: int64

Question 4:How many unique values does the ocean_proximity column have?

ANSWER: 5

In [ ]:
unique_values = data['ocean_proximity'].unique()
len(unique_values)



5

Question 5: What's the average value of the median_house_value for the houses located near the bay?

Answer: 249433.98

In [ ]:
data.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [ ]:
grouped_data = data.groupby('ocean_proximity')['median_house_value'].agg('mean')

In [ ]:
avg_value = grouped_data.get(key='NEAR OCEAN')

In [ ]:
round(avg_value,2)

249433.98

Question 6:
Calculate the average of total_bedrooms column in the dataset.
Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
Now, calculate the average of total_bedrooms again.
Has it changed?

Answer: No

In [ ]:
mean_1= data['total_bedrooms'].mean()

In [ ]:
mean_2 = (data['total_bedrooms'].fillna(mean_1)).mean()

In [ ]:
print( f' mean before replacing null values: {round(mean_1,3)}, mean after replacing null values: {round(mean_2,3)}')
print ("The results are the same after replacing the null values ")

 mean before replacing null values: 537.871, mean after replacing null values: 537.871
The results are the same after replacing the null values 


Question 7:
Select all the options located on islands.

Select only columns housing_median_age, total_rooms, total_bedrooms.

Get the underlying NumPy array. Let's call it X.

Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

Compute the inverse of XTX.

Create an array y with values [950, 1300, 800, 1000, 1300].

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

What's the value of the last element of w?

ANSWER: 5.69922946

In [ ]:
data['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [ ]:
data_island = data.copy()

In [ ]:
data_island = data_island[data_island['ocean_proximity'] == 'ISLAND']

In [ ]:
data_island.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5 entries, 8314 to 8318
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           5 non-null      float64
 1   latitude            5 non-null      float64
 2   housing_median_age  5 non-null      float64
 3   total_rooms         5 non-null      float64
 4   total_bedrooms      5 non-null      float64
 5   population          5 non-null      float64
 6   households          5 non-null      float64
 7   median_income       5 non-null      float64
 8   median_house_value  5 non-null      float64
 9   ocean_proximity     5 non-null      object 
dtypes: float64(9), object(1)
memory usage: 440.0+ bytes


In [ ]:
data_island.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [ ]:
data_island_columns = data_island.drop(columns=['longitude', 'latitude', 'population', 'households', 'median_income', 'median_house_value', 'ocean_proximity'])


In [ ]:
data_island_columns.head(30)

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [ ]:
import numpy as np


In [ ]:
X = data_island_columns.values
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [ ]:
XTX = X.T@X
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [ ]:
inverse_matrix = np.linalg.inv(XTX)

In [ ]:
inverse_matrix

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [ ]:
y = np.array([950, 1300, 800, 1000, 1300])

In [ ]:
y

array([ 950, 1300,  800, 1000, 1300])

In [ ]:
w = (inverse_matrix @ X.T) @ y

In [ ]:
w

array([23.12330961, -1.48124183,  5.69922946])